name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: "Install"
        run: npm ci

      - name: "Test Angular"
        run: npm run test:angular
      - name: "Test React"
        run: npm run test:react
